apps/survey/urls.py
from django.urls import path

from survey.views import (QuestionListView,
                          QuestionCreateView,
                          QuestionUpdateView,
                          answer_question,
                          like_dislike_question)

urlpatterns = [
    path('', QuestionListView.as_view(), name='question-list'),
    path('question/add/', QuestionCreateView.as_view(), name='question-create'),
    path('question/edit/<int:pk>', QuestionUpdateView.as_view(), name='question-edit'),
    path('question/answer', answer_question, name='question-answer'),
    path('question/like', like_dislike_question, name='question-like'),


]

config/urls.py
"""Main URLs module."""

from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('', include(('apps.survey.urls', 'survey'), namespace='survey')),
    path('registration/login/', LoginView.as_view(), name='login'),
    path('registration/logout/', LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/survey/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
import datetime

from apps.survey.utils import get_current_request


class Question(models.Model):
    created = models.DateField('Creada', auto_now_add=True)
    author = models.ForeignKey(get_user_model(), related_name="questions", verbose_name='Pregunta',
                               on_delete=models.CASCADE)
    title = models.CharField('Título', max_length=200)
    description = models.TextField('Descripción')
    # TODO: Quisieramos tener un ranking de la pregunta, con likes y dislikes dados por los usuarios.

    def get_absolute_url(self):
        return reverse('survey:question-edit', args=[self.pk])

    def user_value(self):
        request = get_current_request()
        try:
            answer = self.answers.get(question=self.pk, author=request.user)
        except Answer.DoesNotExist:
            return 0
        return answer.value

    def user_likes(self):
        request = get_current_request()
        try:
            answer = self.answers.get(question=self.pk, author=request.user)
        except Answer.DoesNotExist:
            return None
        return answer.like

    def ranking(self):
        responses = 10 * self.answers.filter(value__gt=0).count()
        likes = 5 * self.answers.filter(like=True).count()
        dislikes = 3 * self.answers.filter(like=False).count()
        ranking = responses + likes - dislikes
        if self.created == datetime.datetime.now().date() and ranking > 0:
            ranking += 10
        return ranking



class Answer(models.Model):
    ANSWERS_VALUES = ((0,'Sin Responder'),
                      (1,'Muy Bajo'),
                      (2,'Bajo'),
                      (3,'Regular'),
                      (4,'Alto'),
                      (5,'Muy Alto'),)

    question = models.ForeignKey(Question, related_name="answers", verbose_name='Pregunta', on_delete=models.CASCADE)
    author = models.ForeignKey(get_user_model(), related_name="answers", verbose_name='Autor', on_delete=models.CASCADE)
    value = models.PositiveIntegerField("Respuesta", default=0, choices=ANSWERS_VALUES)
    comment = models.TextField("Comentario", default="", blank=True)
    like = models.BooleanField("Like", null=True, blank=True)

apps/survey/views.py
import json

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView
from apps.survey.models import Question, Answer


class QuestionListView(LoginRequiredMixin, TemplateView):
    template_name = 'survey/question_list.html'

    def get_context_data(self, **kwargs):
        context = super(QuestionListView, self).get_context_data(**kwargs)
        # Limitar solo mostrar 20 preguntas
        # context['questions'] = sorted(Question.objects.all()[:20], key=lambda question: -question.ranking())
        context['questions'] = sorted(Question.objects.all(), key=lambda question: -question.ranking())
        return context


class QuestionCreateView(LoginRequiredMixin, CreateView):
    model = Question
    fields = ['title', 'description']
    redirect_url = ''

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class QuestionUpdateView(LoginRequiredMixin, UpdateView):
    model = Question
    fields = ['title', 'description']
    template_name = 'survey/question_form.html'


def answer_question(request):
    data_response = json.loads(request.body)
    question_pk = data_response["question_pk"]
    if not question_pk:
        return JsonResponse({'ok': False})
    try:
        question = Question.objects.filter(pk=question_pk)[0]
        answer = Answer.objects.get(question=question, author=request.user)
        answer.value = data_response["value"]
        answer.save()
    except Answer.DoesNotExist:
        question = Answer.objects.create(question_id=question_pk, author=request.user, value=data_response["value"])

    return JsonResponse({'ok': True})


def like_dislike_question(request):
    data_response = json.loads(request.body)
    question_pk = data_response["question_pk"]
    if not question_pk:
        return JsonResponse({'ok': False})
    try:
        question = Question.objects.filter(pk=question_pk)[0]
        answer = Answer.objects.get(question=question, author=request.user)
        answer.like = data_response["value"]
        answer.save()
    except Answer.DoesNotExist:
        question = Answer.objects.create(question_id=question_pk, author=request.user, like=data_response["value"])
    return JsonResponse({'ok': True})

apps/survey/templates/survey/question_form.html
{% extends 'base.html' %}

{% block content %}
    <h1>Hacer pregunta</h1>
    <div class="d-flex">
        <form method="post">{% csrf_token %}
            {{ form.as_p }}
            <hr>
            <input class="btn btn-primary" type="submit" value="Guardar">
        </form>
    </div>
{% endblock %}

apps/survey/templates/survey/question_list.html
{% extends 'base.html' %}
{% block content %}
  <h1>Preguntas</h1>
  <div class="d-flex flex-column">
      {% for question in questions %}
        <div class="card w-100 my-2 p-3">
          <div class="d-flex flex-row">
            <div class="col-10">
              <i class="far fa-question-circle" title="{{ question.description }}"></i>
              <a class="text-muted" style="text-decoration: none" href="{{ question.get_absolute_url }}"><span class="fw-bold">{{ forloop.counter }}.- {{ question.title }}</span></a>
            </div>
            <div class="col-2">
              <span class="fw-lighter">Autor:</span> {{ question.author }}
            </div>
          </div>
          <br>
          <div class="d-flex justify-content-between">
            <div class="d-flex flex-column col-4">
              <u class="fw-lighter mb-1">Respuesta</u>
              <div>
                  {% for val in '12345' %}
                    <a class="mx-1 answer {% if question.user_value|slugify == val %}fas{% else %}fal{% endif %} fa-star text-decoration-none"
                       data-question="{{ question.pk }}"
                       data-value="{{ val }}" href="#" onclick="__answerQuestion({{ question.pk }}, {{ val }})"></a>
                  {% endfor %}
              </div>
            </div>
            <div class="col-4 d-flex flex-column ">
              <u class="fw-lighter mb-1">Evalúa la pregunta</u>
              <div>
                <a class="mx-1 like {% if question.user_likes == 1 %}fas{% else %}fal{% endif %} fa-thumbs-up text-decoration-none"
                   href="#" data-question="{{ question.pk }}" data-value="True"></a>
                <a class="mx-1 like {% if question.user_likes == 0 %}fas{% else %}fal{% endif %} fa-thumbs-up fa-flip-both text-decoration-none"
                   href="#" data-question="{{ question.pk }}" data-value="False"></a>
              </div>
            </div>
            <div class="col-2">
              <u class="fw-lighter mb-1">Ranking:</u>
              <div>
                  {{ question.ranking }} pts.
              </div>


            </div>
          </div>
        </div>
      {% empty %}
        <div>No hay preguntas.</div>
      {% endfor %}
  </div>
{% endblock %}

{% block js %}
  <script>
      const csrftoken = getCookie('csrftoken');

      var likes = document.querySelectorAll('.like');
      likes.forEach(function (cb) {
          cb.addEventListener("click", __likes)
      });

      function getCookie(name) {
          let cookieValue = null;
          if (document.cookie && document.cookie !== '') {
              const cookies = document.cookie.split(';');
              for (let i = 0; i < cookies.length; i++) {
                  const cookie = cookies[i].trim();
                  if (cookie.substring(0, name.length + 1) === (name + '=')) {
                      cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                      break;
                  }
              }
          }
          return cookieValue;
      }


      function __answerQuestion(questionId, answer) {
          var url = 'question/answer';
          var data = {question_pk: questionId, value: answer};

          fetch(url, {
              method: 'POST',
              mode: 'same-origin',
              body: JSON.stringify(data),
              headers: {
                  'Content-Type': 'application/json',
                  'X-CSRFToken': csrftoken
              }
          }).then(res => res.json())
              .catch(error => console.error('Error:', error))
              .then(response => {
                  window.location.reload()
              });
      }

      function __likes() {
          var url = 'question/like';
          var data = {question_pk: this.getAttribute('data-question'), value: this.getAttribute('data-value')};

          fetch(url, {
              method: 'POST',
              mode: 'same-origin',
              body: JSON.stringify(data),
              headers: {
                  'Content-Type': 'application/json',
                  'X-CSRFToken': csrftoken
              }
          }).then(res => res.json())
              .catch(error => console.error('Error:', error))
              .then(response => {
                  window.location.reload()
              });
      }

  </script>

{% endblock %}

apps/templates/base.html
<!doctype html>
<html lang="es" class="h-100">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <title>CW Test</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
          integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

    <style>

    </style>

</head>
<body class="d-flex flex-column h-100">

<header>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Test Claritywave</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/">Home</a>
                    </li>
                    {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'survey:question-create' %}">Crear Pregunta</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                        </li>
                    {% else %}

                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'login' %}">Login</a>
                        </li>
                    {% endif %}

                </ul>

            </div>
        </div>
    </nav>
</header>

<!-- Begin page content -->
<main class="flex-shrink-0">
    <div class="container mt-5 pt-4">
        {% block content %}

        {% endblock %}
    </div>
</main>

<footer class="footer mt-auto py-3 bg-light">
    <div class="container">
        <span class="text-muted">Claritywave.</span>
    </div>
</footer>

</body>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
{% block js %}{% endblock %}
</html>